dist: trusty
sudo: false
language: go

go:
- "1.12.4"

os:
  - linux
  - osx

before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_76567b581e11_key -iv $encrypted_76567b581e11_iv -in gogetcookie.sh.enc -out scripts/gogetcookie.sh -d;
  fi

env:
- GO111MODULE=on

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933#issuecomment-199429151
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then bash scripts/gogetcookie.sh ; fi
- go get ./...

script:
- make build
- make test
- make vet

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then sudo ln -s /usr/local/Cellar/coreutils/*/libexec/gnubin/sha256sum /usr/local/bin/sha256sum ; fi
- make dist

deploy:
  provider: releases
  draft: true
  api_key:
    secure: Ip8VIupp4Z3gYr6+j2Gtyu9GbIOlYdrgCcpOwrTXsl+mpLBMhDJZcOJLMWDX8Jx3vv5CYdrsR4j7O44HBhkdAsC4mHmgWuvMlAEC8dB7q/G8dIRUR4HN7Df4Erj95xTi/AAIW4XUAk7YbQU1emg1zycrKLzvG3LjbYtFrGvHTzWZA8P9FpvGyPj29eY0twkP3QL8JP1j2rcjB4SDyJ2QWUe37X8iYCOR/oRTx7XvweJ1fwQ5GxyR3wt49Jqaes8FxxsN3OEB7X4sBip+caqtNnUZHbtQMX39Jya4rN3fd44gr5UE7VWLq9/Ya4fSfCOKLM8NrqXdavj/vk7JUanxp7SbfHQKtKN1rCzG6L9Vt5zJaTNHy+bFhGjqpH8mgpBNgI2Htqtnc8+O8hVAfY9UHm5TMb/4hoTk6TN7NVGtXDK/0QHOT6NYWiqBGFqpQrT6xtRNcWoLRsZBFWetShir6rIXaioVvtva4t+nOlw/pyQI7PwQMe2mpu4SRoJFeWI30RaxnlmKP6r5sr116HTtKhNksHsMnARG9dc3VFtjwBZn68udUHlmJrf+nX99eVC3UTK2IC004LHcyoVXTGPFKD+4gasBqDnVqWCv9hTQB8qJfLB08+w3SXtcinhZlbYLm22pmZVb6gXyEaWnllAl5TKqihYfQl3OFe6xt6LbIQg=
  file: dist/terraform-provider-virtualbox*
  file_glob: true
  skip_cleanup: true
  tag_name: $TRAVIS_TAG
  on:
    repo: terra-farm/terraform-provider-virtualbox
    tags: true
