[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.7"

[[constraint]]
  branch = "master"
  name = "github.com/pyToshka/go-virtualbox"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[prune]
  go-tests = true
  unused-packages = true
